# Site
name: "Thich Cay Magazine"
description: "Sauce & Cooking."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "thichcayvn@gmail.com"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-menus
  
authors:
  sal:
    name: Sal
    site: https://www.thichcay.com
    avatar: /assets/images/avatar1.jpg
    bio: "Hello world"
    email: thichcayvn@gmail.com
    twitter: https://twitter.com/thichcayvn

  jane:
    name: Jane
    site: https://www.thichcay.net
    avatar: /assets/images/avatar2.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: thichcayvn@gmail.com
    twitter: https://twitter.com/thichcayvn

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
